### ISSUE TITLE
adding custom subdomains 

### ISSUE THREAD

**Issue by quinnliu** [sleirsgoevy/ngrok-free#1]
@sleirsgoevy Great repo! If I want to add custom subdomains do you have any ideas on how to do this? Happy to discuss privately wangzhaoliuq@protonmail.com

**Comment by quinnliu** [comment]
I'm also getting this error when running a simple node.js server 

```
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "ngrok.py", line 90, in copy_thread
    sock2.write(buf)
  File "/Users/qliu/Documents/ngrok-free/muxado/stream.py", line 113, in write
    self.stream.send(b)
  File "/Users/qliu/Documents/ngrok-free/muxado/stream.py", line 83, in send
    with self.lock: Stream.send(self, data)
  File "/Users/qliu/Documents/ngrok-free/muxado/stream.py", line 42, in send
    if self.closed: raise BrokenPipeError()
BrokenPipeError
```
